# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Update team"
  lane :update_team do
    update_project_team(path: "BecomeAPresenter.xcodeproj", teamid: ENV[‘TEAM_ID’])
    update_app_identifier(xcodeproj: "BecomeAPresenter.xcodeproj", plist_path: "BecomeAPresenter/Info.plist", app_identifier: ENV[‘BUNDLE_IDENTIFIER’])
  end

  lane :public do
    sh "fastlane update_team --env public"
  end

  lane :private do
    sh "fastlane update_team --env private"
  end
end
